config {
  type: "assertion",
  description: "Garante que os dados chegaram nas últimas 4 horas"
}

SELECT
  max_ingested_at
FROM (
  SELECT
    -- COALESCE garante que se a tabela estiver vazia, a asserção falhe (retorne uma linha)
    COALESCE(MAX(ingested_at), TIMESTAMP("2000-01-01")) AS max_ingested_at
  FROM
    ${ref("weather_cleaned")}
)
WHERE
  max_ingested_at < TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 4 HOUR)