name: 'Terraform CI/CD'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  id-token: write 

jobs:
  terraform:
    runs-on: ubuntu-latest
    # Movendo as variáveis de ambiente para o nível do JOB para garantir que todos os passos as vejam
    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_weather_api_token: ${{ secrets.OPENWEATHER_API_KEY }}
      TF_VAR_dataform_github_token: ${{ secrets.DATAFORM_GITHUB_TOKEN }}
      TF_VAR_region: "southamerica-east1" # Ou sua região de preferência

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform # Se o seu código TF estiver nesta pasta

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./terraform

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
      working-directory: ./terraform